### ISSUE TITLE
[BUG] Math error

### ISSUE THREAD

**Issue by pandathebeasty** [Stimayk/Quiz#2]
![image](https://github.com/Stimayk/Quiz/assets/64710238/82a6fc28-c460-4a96-b60d-97d80e3261f5)

**Comment by Stimayk** [comment]
> ![image](https://private-user-images.githubusercontent.com/64710238/331701618-82a6fc28-c460-4a96-b60d-97d80e3261f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMzE3NTEsIm5iZiI6MTcxNjAzMTQ1MSwicGF0aCI6Ii82NDcxMDIzOC8zMzE3MDE2MTgtODJhNmZjMjgtYzQ2MC00YTk2LWI2MGQtOTdkODBlMzI2MWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDExMjQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZDFmYjgwNzM2OWY1MzVlNWZhZGQwNzYyNjZkZDZmNTM4YmY2NTVhYzYxZWVlZGU5NmQ1MWNhMjRmODI1ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c5P33QVQPdX4z7z7GxWjxRW3Ekxd6mZ2ZJwMiBJhItw)

Fixed with new release
